server:
  port: 8888

spring:
  mvc:
    dispatch-options-request: true
  main:
    web-application-type: reactive
  application:
    name: Gateway
  cloud:
    discovery:
      enabled: true
    gateway:
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOriginPatterns: "*"
            allowCredentials: true
            allowedMethods: "*"
            allowedHeaders: "*"
eureka:
  instance:
    hostname: localhost
